backend/project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('teste/', views.teste_view),
    path('good', views.good_view),
    path('', views.index_view),
    path('tarefas/', include('tarefas.urls'))
]

backend/tarefas/urls.py
from django.urls import path, include
from rest_framework.decorators import api_view
from rest_framework.routers import DefaultRouter
from . import api_views
from . import views


app_name = 'tarefas'

urlpatterns = [
    path('', views.tarefas_home, name='home'),
    path('adicionar/', views.tarefas_adicionar, name='adicionar'),
    path('remover/<int:id>', views.tarefas_remover, name='remover'),
    path('editar/<int:id>', views.tarefas_editar, name='editar'),
    path('api/', api_views.listar_tarefas, name='listar_tarefas'),
]

backend/tarefas/models.py
from django.db import models

# Create your models here.
class TarefaModel(models.Model):
    nome = models.CharField(max_length=100) # "CharField" é basicamente uma string e poderá ter, no máximo, 100 caracteres
    descricao = models.TextField(null=True, blank=True) # É um campo de texto maior e pode ser vazio (é o que está configurado em seus parâmetros)
    concluido = models.BooleanField(default=False)
    data_criacao = models.DateTimeField(auto_now_add=True) # A partir do momento que a tarefa for criada, a data dela será setada

    def __str__(self):
        return self.nome

backend/tarefas/forms.py
from django import forms
from .models import TarefaModel # O "." significa para pegar arquivos a partir da pasta que estamos atualmente

class TarefaForm(forms.ModelForm): # O django oferece uma interface de  criação de formulários (ModelForm), onde podemos criar um formulário automaticamente a partir de modelos
    class Meta: # A classe Meta é uma classe de configuração para o nosso formulário
        model = TarefaModel # Modelo que iremos usar para criar o nosso forms
        fields = [ # Diz para o HTML quais campos do model ele deve considerar ao fazer o formulário
            'nome',
            'descricao',
            'concluido'
        ]

backend/project/views.py
from django.http import HttpResponse

def teste_view(request):
    return HttpResponse("Essa é a rota de teste!")
def good_view(request):
    return HttpResponse("Essa é uma rota para good!")
def index_view(request):
    return HttpResponse("<h1>Bem vindo!</h1>")

backend/tarefas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TarefaForm
from .models import TarefaModel
from django.http import HttpRequest, HttpResponse


# Create your views here.
def tarefas_home(request):
    contexto = {
        "nome": "Sara",
        'tarefas': TarefaModel.objects.all() # Estamos enviando todos os registros dos objetos tarefas que foram criados
    }
    return render(request, 'tarefas/home.html', contexto)
def tarefas_adicionar(request:HttpRequest):
    print('Carregando view de adicionar tarefas_adicionar')
    if request.method == 'POST':
        formulario = TarefaForm(request.POST) # Pega todas as informações do formulário
        if formulario.is_valid(): # Verifica se as informações do formulário são válidas
            formulario.save() # Se as informações forem válidas, salva os dados
            return redirect('tarefas:home')

    contexto = {
        'form': TarefaForm
    }
    return render(request, 'tarefas/adicionar.html', contexto)
def tarefas_remover(request:HttpRequest, id):
    tarefa = get_object_or_404(TarefaModel ,id = id) # Ele vai tentar obter um item do banco de dados, se o objeto não for encontrado, vai retornar um erro 404
    tarefa.delete()
    return redirect('tarefas:home')
def tarefas_editar(request:HttpRequest, id):
    tarefa = get_object_or_404(TarefaModel, id=id)
    if request.method == 'POST':
        formulario = TarefaForm(request.POST, instance=tarefa)
        if formulario.is_valid():
            formulario.save()
            return redirect('tarefas:home')
    formulario = TarefaForm(instance=tarefa)  # Cria um formulário novo, mas com os dados já inseridos (Esses dados vem da variável "tarefa" que acessamos com o id)
    contexto = {
        'form': formulario
    }
    return render(request, 'tarefas/editar.html', contexto)

backend/tarefas/templates/tarefas/adicionar.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Tarefa</title>
</head>
<body>
    <h1>Adicione suas Tarefas Aqui</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Adicionar">
    </form>
</body>
</html>

backend/tarefas/templates/tarefas/editar.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Tarefa</title>
</head>
<body>
    <h1>Edite suas tarefas aqui</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Adicionar">
    </form>
</body>
</html>

backend/tarefas/templates/tarefas/home.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tarefas</title>
</head>
<body>
    <h1>Bem vinda, {{ nome }}</h1>
    <p>Adicione, edite ou remova tarefas</p>
    <table border="1">
        <thead>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Situação</th>
            <th>Criado em:</th>
        </thead>
        <tbody>
            {% for tarefa in tarefas %}
                <tr>
                    <td>{{tarefa.nome}}</td>
                    <td>{{tarefa.descricao}}</td>
                    <td>{{tarefa.concluido}}</td>
                    <td>{{tarefa.data_criacao}}</td>
                    <td><a href="{% url 'tarefas:editar' tarefa.id %}">Editar Tarefa</a></td>
                    <td><a href="{% url 'tarefas:remover' tarefa.id %}">Remover Tarefa</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'tarefas:adicionar' %}">Adicionar Tarefa</a>
</body>
</html>